# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod ‘MJExtension’
pod ‘AFNetworking’, ‘~> 3.0’
pod 'SDAutoLayout', '~> 2.1.3'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
pod 'SDCycleScrollView','~> 1.64'

